# -*- coding: utf-8 -*-
"""Data Preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgvDUdjmQSPwa04UQQsIJ6p7BqXDeJtm
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

# 1. Load Data (Gunakan pemisah titik koma sesuai format asli)
df = pd.read_csv("DATA AWS TANGSEL 21-25.csv", sep=";")

# 2. Konversi kolom tgl_data menjadi format Waktu (Datetime)
df['tgl_data'] = pd.to_datetime(df['tgl_data'], errors='coerce', format='mixed')

# 3. Paksa kolom yang error menjadi numerik (yang rusak otomatis jadi kosong/NaN)
kolom_bermasalah = ['rr', 'tt_air_max', 'rh_avg']
for col in kolom_bermasalah:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print("Tahap 1 Selesai. Dimensi Data:", df.shape)

for i, col in enumerate(df.columns):
    print(i, col)

# 1. Filter semua baris yang memiliki minimal 1 nilai kosong
df_kosong = df[df.isnull().any(axis=1)].copy()

# 2. Ekstraksi Tahun, Tanggal, dan Jam untuk pencatatan
df_kosong['Tahun'] = df_kosong['tgl_data'].dt.year
df_kosong['Tanggal'] = df_kosong['tgl_data'].dt.date
df_kosong['Jam'] = df_kosong['tgl_data'].dt.time

# 3. Sortir berdasarkan waktu agar mudah melihat dari jam berapa sampai jam berapa
df_kosong = df_kosong.sort_values(by='tgl_data')

# 4. Simpan ke dalam CSV baru sebagai bukti/laporan
kolom_laporan = ['tgl_data','rr']
df_kosong[kolom_laporan].to_csv("Log_Data_Kosong_Tercatat_kondisi_1.csv", index=False)

print(f"Laporan berhasil dibuat! Ada {len(df_kosong)} baris data kosong yang telah dicatat di 'Log_Data_Kosong_Tercatat_kondisi_1.csv'")

from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.copy(
    "Log_Data_Kosong_Tercatat_kondisi_1.csv",
    "/content/drive/MyDrive/Log_Data_Kosong_Tercatat_kondisi_1.csv"
)

# 1. Pengecekan dan Penghapusan Data Duplikat
jumlah_duplikat = df.duplicated().sum()
df = df.drop_duplicates()
print(f"Ditemukan dan dihapus {jumlah_duplikat} baris data duplikat.")

# 2. Pemusnahan Data Kosong (Sesuai instruksi)
df_bersih = df.dropna().copy()
print(f"Sisa data setelah cleansing mutlak: {len(df_bersih)} baris.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load Data Revisi (Gunakan pemisah titik koma)
df = pd.read_csv("DATA AWS TANGSEL 21-25.csv", sep=";")

# 2. Konversi kolom tgl_data menjadi format Waktu (Datetime)
df['tgl_data'] = pd.to_datetime(df['tgl_data'])

# 3. Paksa kolom Hujan menjadi numerik (data teks yang rusak akan menjadi kosong/NaN)
df['Hujan (rr)'] = pd.to_numeric(df['Hujan (rr)'], errors='coerce')

print("Tahap 1 Selesai. Dimensi Data Saat Ini:", df.shape)

# 1. Isolasi semua baris yang Hujan (rr)-nya kosong
df_kosong = df[df['Hujan (rr)'].isnull()].copy()

# 2. Ekstraksi Tahun, Tanggal, dan Jam untuk pencatatan riwayat
df_kosong['Tahun'] = df_kosong['tgl_data'].dt.year
df_kosong['Tanggal'] = df_kosong['tgl_data'].dt.date
df_kosong['Jam'] = df_kosong['tgl_data'].dt.time

# 3. Sortir kronologis dari jam ke jam
df_kosong = df_kosong.sort_values(by='tgl_data')

# 4. Simpan ke dalam CSV baru sebagai bukti/laporan
df_kosong.to_csv("Log_Data_Hujan_Kosong.csv", index=False)

print(f"Laporan berhasil dibuat! {len(df_kosong)} baris data kosong telah direkam ke 'Log_Data_Hujan_Kosong.csv'")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load Data Revisi (Gunakan pemisah titik koma)
df = pd.read_csv("DATA AWS TANGSEL 21-25.csv", sep=";")

# 2. Konversi kolom tgl_data menjadi format Waktu (Datetime)
df['tgl_data'] = pd.to_datetime(df['tgl_data'])

# 3. Paksa kolom Hujan menjadi numerik (data teks yang rusak akan menjadi kosong/NaN)
df['Hujan (rr)'] = pd.to_numeric(df['Hujan (rr)'], errors='coerce')

print("Tahap 1 Selesai. Dim, df.shape)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files  # Modul wajib untuk fitur download di Google Colab

# 1. Load Data Revisi (Gunakan pemisah titik koma)
df = pd.read_csv("DATA AWS TANGSEL 21-25.csv", sep=";")

# 2. Konversi kolom tgl_data menjadi format Waktu (Datetime)
df['tgl_data'] = pd.to_datetime(df['tgl_data'])

# 3. Paksa kolom Hujan menjadi numerik (data teks yang rusak akan menjadi kosong/NaN)
df['Hujan (rr)'] = pd.to_numeric(df['Hujan (rr)'], errors='coerce')

print("Tahap 1 Selesai. Dimensi Data Saat Ini:", df.shape)

# 4. Simpan dataframe yang sudah distandardisasi ke dalam file CSV baru
nama_file = "Data_Tahap1_Standardisasi.csv"
df.to_csv(nama_file, index=False)

# 5. Trigger eksekusi download otomatis ke komputer lokal BOSS
files.download(nama_file)

df

import pandas as pd

# Baca file CSV
df = pd.read_csv("arg tangsel 2021-2025.csv")

# Konversi datetime
df['tgl_data'] = pd.to_datetime(df['tgl_data'])

# Ambil hanya data pada menit 00
df_perjam = df[df['tgl_data'].dt.minute == 0].copy()

# Simpan hasil
df_perjam.to_excel("hasil_perjam.xlsx", index=False)

print("Selesai!")
print(f"Data awal : {len(df)}")
print(f"Data per jam : {len(df_perjam)}")

import pandas as pd

# 1. Membaca file data
# Gunakan baris ini jika file Anda berformat CSV seperti yang diunggah (pemisah ';')
file_path = 'DATA AWS TANGSEL 21-25.csv'
df = pd.read_csv(file_path, sep=';')

# ALTERNATIF: Jika di Google Colab Anda menggunakan file Excel (.xlsx), hapus tanda pagar di bawah ini:
# file_path = 'arg tangsel 2021-2025.xlsx'
# df = pd.read_excel(file_path)

# 2. Mengonversi kolom tgl_data ke format datetime
df['tgl_data'] = pd.to_datetime(df['tgl_data'])

# 3. Memfilter data hanya untuk menit ke-00
# Langkah ini otomatis menghapus menit 10, 20, 30, 40, dan 50
df_filtered = df[df['tgl_data'].dt.minute == 0].copy()

# 4. Menyimpan hasil filter ke file baru
# Menyimpan kembali ke format CSV
df_filtered.to_csv('aws_tangsel_hourly_filtered.csv', index=False, sep=';')

# ALTERNATIF: Jika ingin menyimpan langsung menjadi file Excel (.xlsx) baru di Colab:
# df_filtered.to_excel('arg_tangsel_hourly_filtered.xlsx', index=False)

print("Proses penyaringan selesai, File baru telah berhasil dibuat.")

import pandas as pd

# 1. Membaca file utama Anda
file_path = 'DATA AWS TANGSEL 21-25 perjam.csv'
df = pd.read_csv(file_path, sep=';')

# ========================================================
# ENGINE: MEMBERSIHKAN DATA ERAT / ERROR FORMAT DI EXCEL
# ========================================================
# Jika kolom 'rh_avg' ada di dalam file Anda, kita bersihkan secara otomatis
if 'rh_avg' in df.columns:
    # Mengubah seluruh kolom menjadi teks untuk deteksi aman
    df['rh_avg'] = df['rh_avg'].astype(str).str.strip()

    # Fungsi cerdas untuk memilah angka
    def fix_rh_values(val):
        try:
            # Mengubah string ke float numerik murni
            num = float(val)
            # Jika angka bernilai ribuan (palsu karena salah format ekspor)
            if num >= 1000:
                return num / 10000
            return num
        except ValueError:
            return val

    df['rh_avg'] = df['rh_avg'].apply(fix_rh_values)

# Jika kolom 'tt_air_avg' juga ingin dibersihkan secara otomatis
if 'tt_air_avg' in df.columns:
    df['tt_air_avg'] = pd.to_numeric(df['tt_air_avg'].astype(str).str.replace(',', '.'), errors='coerce')
# ========================================================

# 2. Mengonversi kolom tgl_data ke format datetime
df['tgl_data'] = pd.to_datetime(df['tgl_data'], dayfirst=True)

# 3. Memfilter data hanya untuk menit ke-00 (Interval 1 Jam)
df_filtered = df[df['tgl_data'].dt.minute == 0].copy()

# 4. Menyimpan hasil bersih ke file excel baru agar langsung bisa dipakai
# Menyimpan langsung ke format .xlsx (Excel asli) agar format angkanya otomatis aman
output_file = 'AWS filteres rh ribuan.xlsx'
df_filtered.to_excel(output_file, index=False)

print(f"Beres, BOSS! File hasil filter telah disimpan ke '{output_file}'.")
print("Semua data ribuan palsu sudah rapi dan tidak akan memicu #VALUE! lagi di Excel Anda.")

import pandas as pd
import matplotlib.pyplot as plt

# Baca data
df = pd.read_csv('arg tangsel perjam.csv', sep=';')

# Konversi datetime
df['tgl_data'] = pd.to_datetime(df['tgl_data'], dayfirst=True)

plt.figure(figsize=(15,5))
plt.plot(df['tgl_data'], df['rr'])

plt.title('Curah Hujan Per Jam')
plt.xlabel('Tanggal')
plt.ylabel('Curah Hujan (mm)')
plt.grid(True)

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('arg tangsel perjam.csv', sep=';')
df['tgl_data'] = pd.to_datetime(df['tgl_data'], dayfirst=True)

# Ambil 7 hari pertama sebagai contoh
sample = df.head(24*7)

plt.figure(figsize=(15,5))
plt.bar(sample['tgl_data'], sample['rr'])

plt.title('Curah Hujan Per Jam')
plt.xlabel('Tanggal')
plt.ylabel('RR (mm)')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('arg tangsel perjam.csv', sep=';')

df['tgl_data'] = pd.to_datetime(df['tgl_data'], dayfirst=True)

df['tanggal'] = df['tgl_data'].dt.date
df['jam'] = df['tgl_data'].dt.hour

pivot = df.pivot_table(
    values='rr',
    index='jam',
    columns='tanggal',
    aggfunc='mean'
)

plt.figure(figsize=(18,6))

plt.imshow(
    pivot,
    aspect='auto',
    interpolation='nearest'
)

plt.colorbar(label='Curah Hujan (mm)')
plt.title('Heatmap Curah Hujan')

plt.ylabel('Jam')
plt.xlabel('Tanggal')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('arg tangsel perjam.csv', sep=';')

df['tgl_data'] = pd.to_datetime(df['tgl_data'], dayfirst=True)

bulanan = df.resample(
    'ME',
    on='tgl_data'
)['rr'].sum()

plt.figure(figsize=(15,5))

plt.plot(bulanan.index,
         bulanan.values,
         marker='o')

plt.title('Total Curah Hujan Bulanan')
plt.xlabel('Bulan')
plt.ylabel('Total Curah Hujan (mm)')
plt.grid()

plt.show()

==============================================================================================

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("DATA AWS TANGSEL 21-25 perjam.csv", sep=';')
df['tgl_data'] = pd.to_datetime(df['tgl_data'], dayfirst=True)

plt.figure(figsize=(16,6))

plt.plot(df['tgl_data'], df['rr'], label='Curah Hujan (mm)')
plt.plot(df['tgl_data'], df['tt_air_avg'], label='Suhu Udara (°C)')
plt.plot(df['tgl_data'], df['rh_avg'], label='Kelembaban (%)')

plt.legend()
plt.grid(True)
plt.title("Perubahan Cuaca Terhadap Waktu")
plt.xlabel("Tanggal")
plt.ylabel("Nilai")

plt.show()

plt.figure(figsize=(8,6))

plt.scatter(
    df['tt_air_avg'],
    df['rr'],
    alpha=0.5
)

plt.xlabel("Suhu Udara (°C)")
plt.ylabel("Curah Hujan (mm)")
plt.title("Hubungan Suhu dan Curah Hujan")

plt.show()

plt.figure(figsize=(8,6))

plt.scatter(
    df['rh_avg'],
    df['rr'],
    alpha=0.5
)

plt.xlabel("Kelembaban (%)")
plt.ylabel("Curah Hujan (mm)")
plt.title("Hubungan Kelembaban dan Curah Hujan")

plt.show()

import seaborn as sns

corr = df[['rr','tt_air_avg','rh_avg']].corr()

plt.figure(figsize=(6,5))

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm',
    vmin=-1,
    vmax=1
)

plt.title("Korelasi Variabel Cuaca")

plt.show()

df['tanggal'] = df['tgl_data'].dt.date
df['jam'] = df['tgl_data'].dt.hour

pivot = df.pivot_table(
    values='rr',
    index='jam',
    columns='tanggal',
    aggfunc='mean'
)

plt.figure(figsize=(18,6))

plt.imshow(
    pivot,
    aspect='auto',
    interpolation='nearest'
)

plt.colorbar(label='Curah Hujan (mm)')
plt.title('Heatmap Curah Hujan')
plt.ylabel('Jam')
plt.xlabel('Tanggal')

plt.show()

import pandas as pd

# Baca data
df = pd.read_csv("arg tangsel perjam.csv", sep=';')

# Hitung duplikat
jumlah_duplikat = df.duplicated().sum()

print(f"Jumlah data duplikat: {jumlah_duplikat}")

import pandas as pd

# Baca data
df = pd.read_csv("DATA AWS TANGSEL 21-25 perjam.csv", sep=';')

# Hitung duplikat
jumlah_duplikat = df.duplicated().sum()

print(f"Jumlah data duplikat: {jumlah_duplikat}")

duplikat_waktu = df[df.duplicated(subset=['tgl_data'], keep=False)]

print(f"Jumlah data dengan waktu duplikat: {len(duplikat_waktu)}")

display(duplikat_waktu.sort_values('tgl_data'))

import pandas as pd

# Baca data
df = pd.read_csv("DATA AWS TANGSEL 21-25 perjam.csv", sep=';')

# Hitung duplikat
jumlah_duplikat = df.duplicated().sum()

print(f"Jumlah data duplikat: {jumlah_duplikat}")

import pandas as pd

# =====================================
# BACA FILE CSV
# =====================================
file_input = "DATA AWS TANGSEL 21-25.csv"  # ganti sesuai nama file

df = pd.read_csv(file_input, sep=";")

# =====================================
# KONVERSI KOLOM TANGGAL
# =====================================
df['tgl_data'] = pd.to_datetime(df['tgl_data'])

# =====================================
# FILTER DATA PER JAM
# Hanya ambil menit = 00
# =====================================
df_perjam = df[
    (df['tgl_data'].dt.minute == 0) &
    (df['tgl_data'].dt.second == 0)
].copy()

# =====================================
# HAPUS FORMAT .000
# =====================================
df_perjam['tgl_data'] = df_perjam['tgl_data'].dt.strftime('%Y-%m-%d %H:%M:%S')

# =====================================
# RESET INDEX
# =====================================
df_perjam.reset_index(drop=True, inplace=True)

# =====================================
# SIMPAN HASIL
# =====================================
output_file = "DATA_AWS_TANGSEL_PERJAM.csv"

df_perjam.to_csv(
    output_file,
    index=False
)

# =====================================
# INFORMASI HASIL
# =====================================
print("="*50)
print("PROSES SELESAI")
print("="*50)
print(f"Jumlah data awal   : {len(df):,}")
print(f"Jumlah data perjam : {len(df_perjam):,}")
print(f"File hasil         : {output_file}")
print("="*50)

# Tampilkan 10 baris pertama
print(df_perjam.head(10))

import pandas as pd

# Load the original AWS data
original_aws_df = pd.read_csv(
    '/content/DATA AWS TANGSEL 21-25 perjam.csv',
    sep=';' # Changed separator to semicolon
)

# Convert 'tgl_data' to datetime
original_aws_df['tgl_data'] = pd.to_datetime(
    original_aws_df['tgl_data'],
    format='%d/%m/%Y %H:%M', # Changed date format to match the data
    errors='coerce'
)

# Check for duplicate 'tgl_data' entries
duplicate_tgl_data = original_aws_df[original_aws_df.duplicated(subset=['tgl_data'], keep=False)]

if not duplicate_tgl_data.empty:
    print(f"There are {len(duplicate_tgl_data)} rows with duplicate 'tgl_data' in the original file.")
    print("Here are the first 20 duplicate entries:")
    display(duplicate_tgl_data.sort_values(by='tgl_data').head(20))
else:
    print("No duplicate 'tgl_data' found in the original 'DATA AWS TANGSEL 21-25 perjam (1).csv' file.")

import pandas as pd

df = pd.read_csv(
    '/content/DATA AWS TANGSEL 21-25 perjam.csv',
    sep=';'
)

df.columns = df.columns.str.strip()

df['tgl_data'] = pd.to_datetime(
    df['tgl_data'],
    format='%d/%m/%Y %H:%M',
    errors='coerce'
)

# Cek jumlah duplikat
jumlah_duplikat = df.duplicated(subset=['tgl_data']).sum()

print(f"Jumlah baris duplikat berdasarkan tgl_data: {jumlah_duplikat}")

# Tampilkan seluruh pasangan duplikat
duplicate_rows = df[
    df.duplicated(subset=['tgl_data'], keep=False)
]

if len(duplicate_rows) > 0:
    print("\nContoh data duplikat:")
    display(
        duplicate_rows
        .sort_values('tgl_data')
        .head(20)
    )
else:
    print("\nTidak ditemukan duplikasi timestamp.")

cek = df['tgl_data'].value_counts()

print(cek.describe())

df.groupby('tgl_data').size().value_counts().sort_index()

duplikat = df[df.duplicated('tgl_data', keep=False)]

print("Duplikat mulai:")
print(duplikat['tgl_data'].min())

print("Duplikat berakhir:")
print(duplikat['tgl_data'].max())

print("Suhu = 0 :", (df['tt_air_avg'] == 0).sum())
print("RH = 0   :", (df['rh_avg'] == 0).sum())
print("RR = 0   :", (df['rr'] == 0).sum())

duplikat = df[df.duplicated('tgl_data', keep=False)]

cek = (
    duplikat
    .groupby('tgl_data')
    .agg({
        'rr': ['nunique'],
        'tt_air_avg': ['nunique'],
        'rh_avg': ['nunique']
    })
)

display(cek.head())

import pandas as pd

df = pd.read_csv(
    '/content/DATA AWS TANGSEL 21-25 perjam.csv',
    sep=';'
)

df['tgl_data'] = pd.to_datetime(
    df['tgl_data'],
    format='%d/%m/%Y %H:%M',
    errors='coerce'
)

# Hitung jumlah nilai 0 pada setiap baris
df['skor_kosong'] = (
    (df['tt_air_avg'] == 0).astype(int) +
    (df['rh_avg'] == 0).astype(int)
)

# Pilih record terbaik untuk setiap timestamp
df_bersih = (
    df.sort_values('skor_kosong')
      .drop_duplicates(subset='tgl_data', keep='first')
      .drop(columns='skor_kosong')
)

print("Jumlah data sebelum :", len(df))
print("Jumlah data sesudah :", len(df_bersih))
print("Timestamp unik      :", df_bersih['tgl_data'].nunique())

print("Duplikat timestamp:",
      df_bersih.duplicated(subset=['tgl_data']).sum())

print(df_bersih.isnull().sum())

print(df_bersih.describe())

import matplotlib.pyplot as plt

df_bersih[['rr','tt_air_avg','rh_avg']].boxplot(figsize=(10,5))
plt.show()

df_bersih.to_csv(
    'DATA_AWS_TANGSEL_BERSIH.csv',
    index=False,
    sep=';'
)

import pandas as pd

df = pd.read_csv(
    '/content/DATA_AWS_TANGSEL_BERSIH.csv',
    sep=';'
)

df.columns = df.columns.str.strip()

df['tgl_data'] = pd.to_datetime(
    df['tgl_data'],
    format='%d/%m/%Y %H:%M',
    errors='coerce'
)

# Cek jumlah duplikat
jumlah_duplikat = df.duplicated(subset=['tgl_data']).sum()

print(f"Jumlah baris duplikat berdasarkan tgl_data: {jumlah_duplikat}")

# Tampilkan seluruh pasangan duplikat
duplicate_rows = df[
    df.duplicated(subset=['tgl_data'], keep=False)
]

if len(duplicate_rows) > 0:
    print("\nContoh data duplikat:")
    display(
        duplicate_rows
        .sort_values('tgl_data')
        .head(20)
    )
else:
    print("\nTidak ditemukan duplikasi timestamp.")

print("Jumlah duplikat tgl_data :",
      df_bersih.duplicated(subset=['tgl_data']).sum())

print("===== CEK DUPLIKAT =====")

print("Jumlah baris            :", len(df_bersih))
print("Timestamp unik          :", df_bersih['tgl_data'].nunique())
print("Duplikat timestamp      :", df_bersih.duplicated(subset=['tgl_data']).sum())
print("Duplikat identik        :", df_bersih.duplicated().sum())

if df_bersih.duplicated(subset=['tgl_data']).sum() == 0:
    print("\n✅ Tidak ditemukan duplikasi timestamp")
else:
    print("\n❌ Masih terdapat duplikasi timestamp")

import pandas as pd

df = pd.read_csv(
    '/content/DATA_AWS_TANGSEL_BERSIH.csv',
    sep=';'
)

# Bersihkan nama kolom
df.columns = df.columns.str.strip()

# Konversi tgl_data sesuai format file
df['tgl_data'] = pd.to_datetime(
    df['tgl_data'].astype(str).str.strip(),
    format='%d/%m/%Y %H:%M:%S',
    errors='coerce'
)

# Cek apakah ada tanggal yang gagal dibaca
print("Jumlah NaT :", df['tgl_data'].isna().sum())

# Cek jumlah duplikat timestamp
jumlah_duplikat = df.duplicated(
    subset=['tgl_data']
).sum()

print(f"Jumlah baris duplikat berdasarkan tgl_data: {jumlah_duplikat}")

# Tampilkan duplikat jika ada
duplicate_rows = df[
    df.duplicated(subset=['tgl_data'], keep=False)
]

if len(duplicate_rows) > 0:
    print("\nContoh data duplikat:")
    display(
        duplicate_rows
        .sort_values('tgl_data')
        .head(20)
    )
else:
    print("\n✅ Tidak ditemukan duplikasi timestamp.")

# Validasi akhir
print("\n===== VALIDASI =====")
print("Jumlah baris       :", len(df))
print("Timestamp unik     :", df['tgl_data'].nunique())
print("Duplikat timestamp :", df.duplicated(subset=['tgl_data']).sum())
print("Duplikat identik   :", df.duplicated().sum())

import pandas as pd

df = pd.read_csv(
    '/content/DATA_AWS_TANGSEL_BERSIH.csv',
    sep=';'
)

print(df.columns)
print(df['tgl_data'].head(20).tolist())

import pandas as pd

df = pd.read_csv(
    '/content/arg tangsel perjam.csv',
    sep=';'
)

# Konversi datetime
df['tgl_data'] = pd.to_datetime(
    df['tgl_data'],
    errors='coerce'
)

print("===== CEK DUPLIKAT =====")

print("Jumlah baris            :", len(df))
print("Timestamp unik          :", df['tgl_data'].nunique())
print("Duplikat timestamp      :", df.duplicated(subset=['tgl_data']).sum())
print("Duplikat identik        :", df.duplicated().sum())

if df.duplicated(subset=['tgl_data']).sum() == 0:
    print("\n✅ Tidak ditemukan duplikasi timestamp")
else:
    print("\n❌ Masih terdapat duplikasi timestamp")

df1 = df.drop_duplicates()

print("Sebelum :", len(df))
print("Sesudah :", len(df1))

print("Jumlah baris            :", len(df1))
print("Timestamp unik          :", df1['tgl_data'].nunique())
print("Duplikat timestamp      :", df1.duplicated(subset=['tgl_data']).sum())
print("Duplikat identik        :", df1.duplicated().sum())

duplikat = df1[df1.duplicated(subset=['tgl_data'], keep=False)]

for waktu in duplikat['tgl_data'].unique()[:10]:
    print("\n", waktu)
    display(
        duplikat[duplikat['tgl_data'] == waktu]
    )

duplikat = df1[df1.duplicated(subset=['tgl_data'], keep=False)]

print("Jumlah baris duplikat:", len(duplikat))

display(
    duplikat
    .sort_values('tgl_data')
    .head(50)
)

print("Jumlah NaT:", df1['tgl_data'].isna().sum())

import pandas as pd

# Load the data from the specified CSV file
df_duplicates = pd.read_csv('/content/arg tangsel perjam.csv', sep=';')

# Convert 'tgl_data' to datetime, explicitly setting the format to DD/MM/YYYY HH:MM
df_duplicates['tgl_data'] = pd.to_datetime(df_duplicates['tgl_data'], format='%d/%m/%Y %H:%M', errors='coerce')

print("===== DUPLICATE DATA ANALYSIS =====

import pandas as pd

# Load the data again to inspect original string values
df_raw = pd.read_csv('/content/arg tangsel perjam.csv', sep=';')

# Perform the conversion with the corrected format
df_raw['tgl_data_converted'] = pd.to_datetime(df_raw['tgl_data'], format='%d/%m/%Y %H:%M', errors='coerce')

# Filter rows where conversion resulted in NaT
nat_rows = df_raw[df_raw['tgl_data_converted'].isna()]

print("\n===== ORIGINAL 'tgl_data' VALUES THAT RESULTED IN NaT =====")
if not nat_rows.empty:
    print(f"Total {len(nat_rows)} rows had 'tgl_data' that could not be converted.")
    print("Here are the original 'tgl_data' string values for the first 20 such rows:")
    display(nat_rows[['tgl_data', 'tgl_data_converted']].head(20))
else:
    print("No 'tgl_data' values resulted in NaT upon conversion.")

import pandas as pd

# Load data
df = pd.read_csv('tangsel_data.csv', sep=';')

# Pastikan kolom tgl_data bertipe datetime dengan format yang benar
df['tgl_data'] = pd.to_datetime(df['tgl_data'], format='%d/%m/%Y %H:%M')

# Filter jam 23:50
df_2350 = df[df['tgl_data'].dt.hour == 23 &
             (df['tgl_data'].dt.minute == 50)].reset_index(drop=True)

# Tampilkan hasil
print("Data jam 23:50 setiap hari:")
print(df_2350)
print(f"\nTotal baris ditemukan: {len(df_2350)}")

# Simpan ke CSV baru (opsional)
df_2350.to_csv('data_2350.csv', index=False)
print("\nDisimpan ke data_2350.csv")

import pandas as pd
from google.colab import files

# Load data
df = pd.read_csv('tangsel_data.csv', sep=';')

# Pastikan kolom tgl_data dalam format datetime
df['tgl_data'] = pd.to_datetime(df['tgl_data'], format='%d/%m/%Y %H:%M')

# Filter hanya baris yang jamnya 23:50
df_2350 = df[
    (df['tgl_data'].dt.hour == 23) &
    (df['tgl_data'].dt.minute == 50)
]

print(f"Jumlah baris jam 23:50: {len(df_2350)}")
print(df_2350)

# ✅ Simpan ke CSV baru
df_2350.to_csv('hasil_2350.csv', index=False)

# ✅ Download otomatis
files.download('hasil_2350.csv')

import pandas as pd
from google.colab import files

# Upload file
uploaded = files.upload()

import io

# ✅ Tambahkan sep=';' karena pemisahnya titik koma
df = pd.read_csv(io.BytesIO(uploaded['tangsel_data (3).csv']), sep=';')

# Pastikan kolom tgl_data dalam format datetime
df['tgl_data'] = pd.to_datetime(df['tgl_data'], format='%d/%m/%Y %H:%M')

# Filter hanya baris yang jamnya 23:50
df_2350 = df[
    (df['tgl_data'].dt.hour == 23) &
    (df['tgl_data'].dt.minute == 50)
].copy()

# Sort berdasarkan tanggal
df_2350 = df_2350.sort_values('tgl_data').reset_index(drop=True)

print(f"Jumlah baris jam 23:50: {len(df_2350)}")
print(df_2350)

# Simpan dan download
df_2350.to_csv('hasil_2350.csv', index=False)
files.download('hasil_2350.csv')

import pandas as pd
from google.colab import files
import io

# Upload file
uploaded = files.upload()

# ✅ Ambil nama file otomatis (apapun namanya)
nama_file = list(uploaded.keys())[0]
print(f"File yang diupload: {nama_file}")

# ✅ Tambahkan sep=';' karena pemisahnya titik koma
df = pd.read_csv(io.BytesIO(uploaded[nama_file]), sep=';')

# Pastikan kolom tgl_data dalam format datetime
df['tgl_data'] = pd.to_datetime(df['tgl_data'], format='%d/%m/%Y %H:%M')

# Filter hanya baris yang jamnya 23:50
df_2350 = df[
    (df['tgl_data'].dt.hour == 23) &
    (df['tgl_data'].dt.minute == 50)
].copy()

# Sort berdasarkan tanggal
df_2350 = df_2350.sort_values('tgl_data').reset_index(drop=True)

print(f"Jumlah baris jam 23:50: {len(df_2350)}")
print(df_2350)

# Simpan dan download
df_2350.to_csv('hasil_2350.csv', index=False)
files.download('hasil_2350.csv')

import pandas as pd

# Baca file
df = pd.read_csv(
    '/content/DATA_AWS_TANGSEL_BERSIH.csv',
    sep=';'
)

# Konversi datetime
df['tgl_data'] = pd.to_datetime(
    df['tgl_data'],
    errors='coerce'
)

# Urutkan waktu
df = df.sort_values('tgl_data')

# Ambil tanggal saja
df['tanggal'] = df['tgl_data'].dt.date

hasil = []

for tanggal, grup in df.groupby('tanggal'):

    # Cari jam 00:00:00
    jam_00 = grup[
        (grup['tgl_data'].dt.hour == 0) &
        (grup['tgl_data'].dt.minute == 0) &
        (grup['tgl_data'].dt.second == 0)
    ]

    if len(jam_00) > 0:
        hasil.append(jam_00.iloc[0])
    else:
        # Ambil record terakhir pada hari tersebut
        hasil.append(grup.iloc[-1])

df_perhari = pd.DataFrame(hasil)

# Hapus kolom bantu
df_perhari = df_perhari.drop(columns=['tanggal'])

print("Jumlah data awal :", len(df))
print("Jumlah data per hari :", len(df_perhari))

# Simpan
df_perhari.to_csv(
    'DATA_AWS_TANGSEL_PERHARI.csv',
    sep=';',
    index=False
)

print("Berhasil disimpan: DATA_AWS_TANGSEL_PERHARI.csv")

import pandas as pd

# =====================================================
# 1. BACA DATA
# =====================================================

df = pd.read_csv(
    '/content/arg tangsel perjam.csv',
    sep=';',
    engine='python' # Added engine='python' for more robust parsing
)

df.columns = df.columns.str.strip()

# =====================================================
# 2. KONVERSI DATETIME
# =====================================================

df['tgl_data'] = pd.to_datetime(
    df['tgl_data'],
    dayfirst=True,
    errors='coerce'
)

# =====================================================
# 3. HAPUS DATA TANGGAL TIDAK VALID
# =====================================================

print("Jumlah NaT :", df['tgl_data'].isna().sum())

df = df.dropna(subset=['tgl_data'])

# =====================================================
# 4. HAPUS DUPLIKAT IDENTIK
# =====================================================

print("Jumlah data sebelum :", len(df))

df = df.drop_duplicates()

print("Jumlah data sesudah :", len(df))

# =====================================================
# 5. AMBIL SATU DATA PER HARI
# =====================================================

df = df.sort_values('tgl_data')

df['tanggal'] = df['tgl_data'].dt.date

hasil = []

for tanggal, grup in df.groupby('tanggal'):

    data_jam_00 = grup[
        (grup['tgl_data'].dt.hour == 0) &
        (grup['tgl_data'].dt.minute == 0)
    ]

    if len(data_jam_00) > 0:

        hasil.append(data_jam_00.iloc[0])

    else:

        # ambil waktu terakhir pada hari tersebut
        hasil.append(
            grup.sort_values('tgl_data').iloc[-1]
        )

df_harian = pd.DataFrame(hasil)

# =====================================================
# 6. HAPUS KOLOM BANTU
# =====================================================

df_harian = df_harian.drop(columns=['tanggal'])

# =====================================================
# 7. CEK HASIL
# =====================================================

print("\n===== HASIL ====")
print("Jumlah data harian :", len(df_harian))

display(df_harian.head())

# =====================================================
# 8. SIMPAN
# =====================================================

df_harian.to_csv(
    'ARG_TANGSEL_PERHARI.csv',
    index=False
)

print("\nFile berhasil disimpan:")
print("ARG_TANGSEL_PERHARI.csv")

print(df.head())